os: osx
osx_image: xcode11.2
language: objective-c

#coveralls
before_install: rvm use $RVM_RUBY_VERSION
install: 
  - bundle install
  - pod install
after_success: slather
#end of coveralls

xcode_workspace: ParticleSDK.xcworkspace
xcode_scheme: ParticleSDKPods
xcode_sdk: iphonesimulator13.2
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11

cache: cocoapods

#slack notifications
notifications:
  slack: s:SGT6o8jAzgff7j1dO2XMYRo3
