os: osx
osx_image: xcode11.2
language: objective-c

#coveralls
before_install: rvm use $RVM_RUBY_VERSION
install: 
  - bundle install
  - pod install
after_success: slather
#end of coveralls

xcode_workspace: ParticleSDK.xcworkspace
xcode_scheme: ParticleSDKPods
xcode_sdk: iphonesimulator13.2
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11

cache: cocoapods

#slack notifications
notifications:
  slack:
    secure: RgB9y7dI+1rZLU3EP16Un88z3OZVhkYFf0VEprrL00CTMQGRNfv1bTb+OHEpMhjS4UQkDF5LnezHVXHuHrq1ON5dRrGED1BGcgp0oLB85va76yyfAp7ZP9oG0PR6YS3awVeZrQ+Lb3uONNcZDACom5l8dIt2QPNjM+xmIjueou8fEcINY10Pd964qgLZEtzAjhvkM49vxw+RdZ3q93qnFk2/dilTCYeIVIDIrm2ECIBI1V0kAR+HdDHMT8BhMn7jmS4cetRXW+KPRIDhZ1+NFK4k8kyomOMmAyyiXIKikUiMsdRxF3LRQQZ0g0oEneh08mFk5jj4IkFbFW8MNP5igIMQUAlj231eUW3B9cIJVdi6m2NN4XAFCBVkWZUlmYTZ8rkdJBDxEirtBgUp/2P1Cxs7klHqc5a5+a+l+IrNOD4lwfY+ZBSKJ1LZRX+IwIsgdkx8iODN0dbMHIT+EcxWAg+yWdHgjRsuIXm/Ayf8+zUBms+tRbCOOl+yf/efRejJZ9SAjo2aVYXjwi9LGe/viBfHUziQyDBihwNW9ZwIv35cdBLyvotST5rIxFGM6u7gTzoFWe/u12psgzXmqrXAsh5fjVlx/9OHUHMiQbWBx1jqvloQI7/GwR5PIjgLpNgTxsD3hOP5Uwp4Si+ymKnfWR2Okoq8CRwyaaNEFol15fg=
