os: osx
osx_image: xcode11.2
language: objective-c


xcode_workspace: ParticleSDK.xcworkspace
xcode_scheme: ParticleSDKPods
xcode_sdk: iphonesimulator13.2
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11

cache: cocoapods

